version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blinkmusic-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Добавьте другие переменные окружения для бэкенда (например, DB_URI, JWT_SECRET и т.д.)
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - blinkmusic-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blinkmusic-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000/api
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - blinkmusic-network

networks:
  blinkmusic-network:
    driver: bridge 